// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnuQfHxi_aeY4wqkAzuO4J5qKWS58DMeE',
    appId: '1:316361826153:web:286b257b38b3c1be3ce7f8',
    messagingSenderId: '316361826153',
    projectId: 'sushischeffpro',
    authDomain: 'sushischeffpro.firebaseapp.com',
    storageBucket: 'sushischeffpro.firebasestorage.app',
    measurementId: 'G-WX4PQRNHWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcUNCXQRswrcrH9mI3w6w8GULqk8Ews5s',
    appId: '1:316361826153:android:719843dda9edf4a23ce7f8',
    messagingSenderId: '316361826153',
    projectId: 'sushischeffpro',
    storageBucket: 'sushischeffpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByG69tAHRsodIjU0jACevsgyQhIhN5sF4',
    appId: '1:316361826153:ios:6289a8e8b79015403ce7f8',
    messagingSenderId: '316361826153',
    projectId: 'sushischeffpro',
    storageBucket: 'sushischeffpro.firebasestorage.app',
    iosBundleId: 'com.example.pidkazki2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByG69tAHRsodIjU0jACevsgyQhIhN5sF4',
    appId: '1:316361826153:ios:6289a8e8b79015403ce7f8',
    messagingSenderId: '316361826153',
    projectId: 'sushischeffpro',
    storageBucket: 'sushischeffpro.firebasestorage.app',
    iosBundleId: 'com.example.pidkazki2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnuQfHxi_aeY4wqkAzuO4J5qKWS58DMeE',
    appId: '1:316361826153:web:398b4cabbcab7e1b3ce7f8',
    messagingSenderId: '316361826153',
    projectId: 'sushischeffpro',
    authDomain: 'sushischeffpro.firebaseapp.com',
    storageBucket: 'sushischeffpro.firebasestorage.app',
    measurementId: 'G-Q9BX752ZMK',
  );
}
